name: gnss_location
description: Support for locations produced by a Global Navigation Satellite Systems (GNSS).
dependencies:
  location:
    url: github.com/toitware/toit-location
    version: ^1.0.0
